'use client';
import MenuItem from '@/presenter/component/LeftSidebarMenu/menuItem/MenuItem';

export interface MenuData {
  title: string;
  permisson: string;
  level: number;
  link?: string;
  subMenu: MenuData[];
  isOpen: boolean; // 펼침 여부
}

const LeftSidebarMenu = () => {
  const menuData: MenuData[] = [
    {
      title: '만화',
      permisson: 'write',
      level: 1,
      isOpen: false,
      subMenu: [
        {
          title: '신규등록',
          permisson: 'write',
          link: '/comics/new',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '만화',
          permisson: 'write',
          link: '/comics/all',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '작가',
          permisson: 'write',
          link: '/comics/author/list',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '키워드',
          permisson: 'write',
          link: '/promotion/hashtag',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '캐릭터 정보',
          permisson: 'write',
          level: 2,
          isOpen: false,
          subMenu: [
            {
              title: '캐릭터 태그',
              permisson: 'write',
              link: '/characterTag/list',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '캐릭터 리스트',
              permisson: 'write',
              link: '/character/list',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
          ],
        },
        {
          title: '인기 검색어 (화이트리스트)',
          permisson: 'write',
          link: '/searchKeyword/list',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '테마관',
          permisson: 'write',
          link: '/theme/1',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '기획전',
          permisson: 'write',
          link: '/promotion/eventTheme',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '프로모션 정보 배너',
          permisson: 'write',
          link: '/promotionPeriod',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
      ],
    },
    {
      title: '카테고리',
      permisson: 'write',
      level: 1,
      isOpen: false,
      subMenu: [
        {
          title: '메인',
          permisson: 'write',
          level: 2,
          isOpen: false,
          subMenu: [
            {
              title: '월',
              permisson: 'write',
              link: '/category/daily/mon',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '화',
              permisson: 'write',
              link: '/category/daily/tue',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '수',
              permisson: 'write',
              link: '/category/daily/wed',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '목',
              permisson: 'write',
              link: '/category/daily/thu',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '금',
              permisson: 'write',
              link: '/category/daily/fri',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '토',
              permisson: 'write',
              link: '/category/daily/sat',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '일',
              permisson: 'write',
              link: '/category/daily/sun',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: 'TOP',
              permisson: 'write',
              link: '/category/daily/popular',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
          ],
        },
        {
          title: '완결',
          permisson: 'write',
          link: '/category/complete',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '추천',
          permisson: 'write',
          link: '/category/popular',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '신작',
          permisson: 'write',
          link: '/category/new',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '장르',
          permisson: 'write',
          link: '/genres',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '성인',
          permisson: 'write',
          link: '/category/mature',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '신작 시리즈',
          permisson: 'write',
          link: '/category/new_series',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: 'ArtWorks',
          permisson: 'write',
          link: '/artworks',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: 'Promo',
          permisson: 'write',
          link: '/promo',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '독점무료',
          permisson: 'write',
          link: '/category/originFree',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '망가',
          permisson: 'write',
          link: '/category/manga',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
      ],
    },
    {
      title: '배너',
      permisson: 'write',
      level: 1,
      isOpen: false,
      subMenu: [
        {
          title: '메인',
          permisson: 'write',
          link: '/banner/main_v2',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '이벤트',
          permisson: 'write',
          link: '/banner/event',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '플로팅',
          permisson: 'write',
          link: '/banner/floating',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '유저 배너',
          permisson: 'write',
          link: '/userBanner/all',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '랜덤 유저 배너',
          permisson: 'write',
          link: '/randomUserBanner/all',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '액션 레이어 관리',
          permisson: 'write',
          link: '/actionLayer',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '메인 중앙',
          permisson: 'write',
          link: '/banner/theme',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '로고 관리',
          permisson: 'write',
          link: '/logoList/1',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '결제',
          permisson: 'write',
          link: '/paymentBanner',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
      ],
    },
    {
      title: '프로모션',
      permisson: 'write',
      level: 1,
      isOpen: false,
      subMenu: [
        {
          title: '선물함',
          permisson: 'write',
          link: '/giftbox',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '등급 설정',
          permisson: 'write',
          link: '/grade',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '친구 초대',
          permisson: 'write',
          link: '/giftbox/inviteRewardList',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '굿즈 리스트',
          permisson: 'write',
          link: '/promotion/goods/ticket',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '전체 소장',
          permisson: 'write',
          link: '/promotion/unlock_all_discount',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '전체 소장 (개별설정)',
          permisson: 'write',
          link: '/promotion/unlock_all_discount_list',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '이벤트 목록',
          permisson: 'write',
          link: 'event/list',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '회차 유도',
          permisson: 'write',
          link: '/promotion/induce/all',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: 'Dailyreward (룰렛)',
          permisson: 'write',
          link: '/event/daily/reward/list',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '이상형 월드컵',
          permisson: 'write',
          link: '/event/daily/reward/list',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
      ],
    },
    {
      title: '결제 상품',
      permisson: 'write',
      level: 1,
      isOpen: false,
      subMenu: [
        {
          title: '결제 상품 목록',
          permisson: 'write',
          link: '/paymentList',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '결제 수단 관리',
          permisson: 'write',
          link: '/paymentMethod',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '국가별 통화 선택',
          permisson: 'write',
          link: '/localeCurrency',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '상품 그룹 관리',
          permisson: 'write',
          link: '/productGroup',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
      ],
    },
    {
      title: '유저',
      permisson: 'write',
      level: 1,
      isOpen: false,
      subMenu: [
        {
          title: '유저 리스트',
          permisson: 'write',
          link: '/users',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '유저 차단 리스트',
          permisson: 'write',
          link: '/userblock',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '유저 Visitor ID 차단 리스트',
          permisson: 'write',
          link: '/visitoridBlock',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '공지사항',
          permisson: 'write',
          link: '/notice',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: 'FAQ',
          permisson: 'write',
          link: '/faq',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '신고/문의',
          permisson: 'write',
          link: '/userSubmit',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '댓글 관리',
          permisson: 'write',
          level: 2,
          isOpen: false,
          subMenu: [
            {
              title: '댓글 필터',
              permisson: 'write',
              link: '/users/comment/filter',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '댓글 검수',
              permisson: 'write',
              link: '/users/comment/list',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
          ],
        },
      ],
    },
    {
      title: '앱',
      permisson: 'write',
      level: 1,
      isOpen: false,
      subMenu: [
        {
          title: '앱 푸쉬',
          permisson: 'write',
          link: '/app/push',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '앱 업로드',
          permisson: 'write',
          link: '/app/upload',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '앱 버전 관리',
          permisson: 'write',
          link: '/app/version',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
      ],
    },
    {
      title: '통계',
      permisson: 'write',
      level: 1,
      isOpen: false,
      subMenu: [
        {
          title: '코인',
          permisson: 'write',
          level: 2,
          isOpen: false,
          subMenu: [
            {
              title: '누적 코인 내역',
              permisson: 'write',
              link: '/statistics/v2/purchase/acc',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '날짜별 코인 내역',
              permisson: 'write',
              link: '/statistics/v2/purchase/day',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '코인 / 시간별',
              permisson: 'write',
              link: '/statistics/v2/purchase/time',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
          ],
        },
        {
          title: '매출',
          permisson: 'write',
          level: 2,
          isOpen: false,
          subMenu: [
            {
              title: '전체 / 결제',
              permisson: 'write',
              link: '/statistics/v2/payment/all',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '자동충전 결제내역',
              permisson: 'write',
              link: '/statistics/v2/payment/recurring',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '시간 / 결제',
              permisson: 'write',
              link: '/statistics/v2/payment/time',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '일별 / 결제',
              permisson: 'write',
              link: '/statistics/v2/payment/day',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '일별 / 첫결제',
              permisson: 'write',
              link: '/statistics/v2/payment/day/first',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '국가별 / 화폐별',
              permisson: 'write',
              link: '/statistics/v2/payment/country/country',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '할인쿠폰 통계',
              permisson: 'write',
              link: '/statistics/v2/payment/discount',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '자동충전 / 멤버십',
              permisson: 'write',
              link: '/statistics/v2/payment/membership',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '결제통계 갱신',
              permisson: 'write',
              link: '/statistics/v2/payment/sync',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '일별 구매 상품',
              permisson: 'write',
              link: '/statistics/v2/performance/product',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
          ],
        },
        {
          title: '작품',
          permisson: 'write',
          level: 2,
          isOpen: false,
          subMenu: [
            {
              title: '만화 - 일자별',
              permisson: 'write',
              link: '/statistics/v2/comic/info',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '만화 - 시간별',
              permisson: 'write',
              link: '/statistics/v2/comic/time',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '회차',
              permisson: 'write',
              link: '/statistics/v2/comic/episode',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '최신회차 판매',
              permisson: 'write',
              link: '/statistics/v2/comic/continueRead',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '전체 구매 - 일자별',
              permisson: 'write',
              link: '/statistics/v2/collection/day/total',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '전체 구매 - 작품별',
              permisson: 'write',
              link: '/statistics/v2/collection/comic/total',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '무료회차 소장',
              permisson: 'write',
              link: '/statistics/v2/collection/free/purchase',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '뷰어 유료회차 소장',
              permisson: 'write',
              link: '/statistics/v2/collection/paid/purchase/comic',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '자동 구독',
              permisson: 'write',
              link: '/statistics/v2/comic/autoPurchase',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '기획전',
              permisson: 'write',
              link: '/statistics/v2/collection/eventTheme',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '기다빵(일별)',
              permisson: 'write',
              link: '/statistics/v2/collection/waitFreeComicDay',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '추천무료(일별)',
              permisson: 'write',
              link: '/statistics/v2/collection/recommendFreeDay',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '신작 오픈 통계',
              permisson: 'write',
              link: '/statistics/v2/comic/firstOpenComic',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '일별 / 작품',
              permisson: 'write',
              link: '/statistics/v2/performance/comicDaily',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
          ],
        },
        {
          title: '회원',
          permisson: 'write',
          level: 2,
          isOpen: false,
          subMenu: [
            {
              title: '회원가입 / 로그인',
              permisson: 'write',
              link: '/statistics/v2/member/sign_in',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '가입통계 / 국가별',
              permisson: 'write',
              link: '/statistics/v2/member/signup/country',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '가입통계 / 시간별',
              permisson: 'write',
              link: '/statistics/v2/member/signUp/time',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '로그인통계 / 국가별',
              permisson: 'write',
              link: '/statistics/v2/member/signin/country',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '로그인통계 / 시간별',
              permisson: 'write',
              link: '/statistics/v2/member/signIn/time',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '사전인증',
              permisson: 'write',
              link: '/statistics/v2/member/already_mature',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '자동인증',
              permisson: 'write',
              link: '/statistics/v2/member/autoAuth',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '그룹',
              permisson: 'write',
              link: '/statistics/v2/member/user_group',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '회원 등급 통계',
              permisson: 'write',
              link: '/statistics/v2/member/user_grade',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '차단 통계',
              permisson: 'write',
              link: '/statistics/v2/member/block',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '방문자 통계',
              permisson: 'write',
              link: '/statistics/v2/member/visitor',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
          ],
        },
        {
          title: '프로모션',
          permisson: 'write',
          level: 2,
          isOpen: false,
          subMenu: [
            {
              title: '선물함',
              permisson: 'write',
              link: '/statistics/v2/giftbox/day',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '시즌패스 통계',
              permisson: 'write',
              link: '/statistics/v2/promotion/seasonPass',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '쿠폰 통계',
              permisson: 'write',
              link: '/statistics/v2/promotion/coupon',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '마케팅 쿠폰 통계',
              permisson: 'write',
              link: '/statistics/v2/promotion/oneTimeCoupon',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '유입 데이터 통계',
              permisson: 'write',
              link: '/statistics/v2/promotion/InflowByCate',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: 'Dailyreward (룰렛)',
              permisson: 'write',
              link: '/statistics/v2/promotion/dailyRewardList',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '굿즈 코인 통계',
              permisson: 'write',
              link: '/statistics/v2/goods/coin',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '친구초대 통계(일별)',
              permisson: 'write',
              link: '/statistics/v2/invite/day',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
          ],
        },
        {
          title: '파트너',
          permisson: 'write',
          level: 2,
          isOpen: false,
          subMenu: [
            {
              title: '파트너 코드',
              permisson: 'write',
              link: '/partnercode',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
            {
              title: '파트너 통계',
              permisson: 'write',
              link: '/statistics/v2/promotion/code',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
          ],
        },
        {
          title: '앱',
          permisson: 'write',
          level: 2,
          isOpen: false,
          subMenu: [
            {
              title: '앱 다운로드',
              permisson: 'write',
              link: '/statistics/v2/app/installStat',
              level: 3,
              isOpen: false,
              subMenu: [],
            },
          ],
        },
      ],
    },
    {
      title: '관리자 계정 컨트롤',
      permisson: 'write',
      level: 1,
      isOpen: false,
      subMenu: [
        {
          title: '관리자 계정 리스트',
          permisson: 'write',
          link: '/master/userList',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '가입 신청 리스트',
          permisson: 'write',
          link: '/master/signupList',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '비활성 계정 리스트',
          permisson: 'write',
          link: '/master/disabledUserList',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
      ],
    },
    {
      title: '기타',
      permisson: 'write',
      level: 1,
      isOpen: false,
      subMenu: [
        {
          title: '환경설정',
          permisson: 'write',
          link: '/preferences',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '수정내역',
          permisson: 'write',
          link: '/editLog',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
        {
          title: '글로벌 설정',
          permisson: 'write',
          link: '/config',
          level: 2,
          isOpen: false,
          subMenu: [],
        },
      ],
    },
  ];

  return (
    <nav className="text-base font-semibold h-full overflow-y-auto">
      {menuData.map((item) => (
        <MenuItem item={item} />
      ))}
    </nav>
  );
};

export default LeftSidebarMenu;
