import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import RecoilRootProvider from './recoilRootProvider';
import cn from 'clsx';
import AuthContext from './context/AuthContext';
import Header from './header/page';

const inter = Inter({ subsets: ['latin'] });

// Metadata가 선언되어 있는 최상위 layout 파일은 client component로 쓸수없기 때문에
// recoilRootProvider.tsx 파일을 만들어서 recoilRootProvider를 client component로 사용한다.
// recoilRootProvider.tsx 파일은 recoilRootProvider를 export default로 내보내고 있다.
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('flex w-full h-full justify-center')}>
        <div className="flex-col flex-[1]">
          <Header />
        </div>
        <div className="flex-col flex-[3] mt-[20px]">
          <AuthContext>
            <RecoilRootProvider>{children}</RecoilRootProvider>
          </AuthContext>
        </div>
      </body>
    </html>
  );
}
