import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import RecoilRootProvider from './recoilRootProvider';
import cn from 'clsx';
import AuthContext from './context/AuthContext';
import HeaderNavBar from '@/presenter/component/headerNavBar/HeaderNavBar';
import LeftSideBarMenu from '@/presenter/component/LeftSidebarMenu/LeftSidebarMenu';
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';

const inter = Inter({ subsets: ['latin'] });

// Metadata가 선언되어 있는 최상위 layout 파일은 client component로 쓸수없기 때문에
// recoilRootProvider.tsx 파일을 만들어서 recoilRootProvider를 client component로 사용한다.
// recoilRootProvider.tsx 파일은 recoilRootProvider를 export default로 내보내고 있다.
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('flex flex-col w-auto h-full justify-center')}>
        <Analytics />
        <SpeedInsights />
        <RecoilRootProvider>
          <HeaderNavBar />
          <div className="container flex flex-row">
            <aside className="sidebar">
              <LeftSideBarMenu />
            </aside>
            <div className="flex flex-row m-[10px]">
              <AuthContext>{children}</AuthContext>
            </div>
          </div>
        </RecoilRootProvider>
      </body>
    </html>
  );
}
